/** Public disclosure grounded in the current writers; freshness is not a physical deletion guarantee. */
export const DATA_DISCLOSURE = [
  { name: 'Account and preferences', data: 'Steam ID, display name, profile and avatar URLs, profile visibility, last library sync time, timezone and visibility flags.', retention: 'Kept until you delete your QIT data; refreshed when you sign in or sync.' },
  { name: 'Library and achievements', data: 'Owned game IDs, names, icons, total and recent playtime, last played time when available, community stats availability, store flags, achievement counts and percentages, locked achievement IDs/names/descriptions, last unlock time, and cache status/timestamps. A compact library index duplicates these signals.', retention: 'Kept until deletion or replacement. Removed games are removed on sync. Achievement freshness is 24 hours for unfinished games, 30 days for completed games, and 7 days for games without stats; a private-achievement marker lasts 1 hour.' },
  { name: 'Friends and pinned players', data: 'Friend and pinned Steam IDs; cached names, profile/avatar URLs, online status and current game when Steam shares them; list visibility and fetch/update times.', retention: 'Pinned players remain until removed or account deletion. Friend snapshots are refreshed after 15 minutes, but old snapshots can remain stored until replaced or deleted.' },
  { name: 'QIT activity', data: 'Rolls, selected games and modes, filters, participant IDs, lobby references, reasons, acceptance/reroll/play timestamps and playtime at selection; events and their metadata; exclusions; challenges, target achievements, unlock evidence and lifecycle timestamps; counters and cached streak/progression statistics.', retention: 'Kept until you delete your QIT data. Temporary exclusions and challenge offers expire for use, but their stored records are not automatically erased by the application.' },
  { name: 'Public friend libraries', data: 'A shared cache keyed by Steam ID containing game IDs, names/icons, playtime and available library signals, or a private/not-found/error status, plus fetch and expiry times.', retention: 'Successful non-QIT libraries are usable for 30 minutes only. Private/not-found results last 5 minutes; errors last 1 minute. Expired Firestore records may remain physically stored until replaced or removed by configured infrastructure cleanup.' },
  { name: 'Game Night lobbies', data: 'Lobby code, host and member IDs, member names/avatars, readiness, library visibility and hidden-playtime flags, join times, filters, counts, votes, vetoes and result slots. Compressed common-library chunks include the shared games and per-player playtime; current chunks may also carry host library and achievement signals.', retention: 'Lobbies expire after 6 hours without a mutation. Their library data stops being used when the lobby expires. Expired documents/chunks can remain physically stored; automatic physical cleanup is not guaranteed by this code.' },
  { name: 'Shared game metadata', data: 'Genres; game/store type, categories, flags, tags, release date, artwork, reviews and parent game ID; concurrent player counts and top-game chart.', retention: 'These are app-level data, shared across users. Genre freshness is 1 day; metadata 7 days (30 days for unknown apps); player counts 10 minutes and charts 5 minutes. Stored records can remain until refreshed. Account deletion does not remove shared game metadata.' },
  { name: 'Sessions, limits and diagnostics', data: 'A sealed __session cookie containing your Steam ID and expiry (or a short sign-in return path); temporary server-memory caches and request limits; hashed user/IP lobby rate-limit records with token counts and update/expiry times. Server error logging uses a fixed context and error type, without Steam payloads, URLs, keys or stacks.', retention: 'Sign-in sessions last up to 7 days; sign-in return state lasts 10 minutes. Public-library memory cache freshness is 5 minutes; other request caches/limits are bounded per instance. Lobby creation limits use a 1-hour window and join limits a 1-minute window. Expired limit documents may remain stored. Hosting log/backup retention is not specified in this repository.' },
] as const;
